#-------------------------------------------------------------------------------
# Name:        Chapter 3
# Purpose:     Section 3.8 Problem 12
#
# Author:      DylanG
#
# Created:     02/24/2025
# Copyright:   (c) DylanG 2025
#-------------------------------------------------------------------------------

import turtle

wn = turtle.Screen()
wn.bgcolor("lightgreen")
wn.title("Clock")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(-90)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(-60)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(-30)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(0)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(30)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(60)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(90)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(120)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(150)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(180)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(210)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")

alex = turtle.Turtle()
alex.stamp()
alex.shape("turtle")
alex.color("blue")
alex.speed(10)
alex.penup()
alex.right(240)
alex.forward(200)
alex.pendown()
alex.forward(20)
alex.penup()
alex.forward(20)
alex.stamp()
alex.shape("turtle")
alex.pendown()

wn.mainloop()